### ISSUE TITLE
Configurable Messages File

### ISSUE THREAD

**Issue by Sepshun** [AtriusX/Waystones#3]
It could be nice to have a YML file dedicated to configuring the messages displayed by the plugin for various actions, such as initiating a warp, successfully warping, canceling a warp, or getting info of a waystone. This could also be expanded to include the lore on linked Warp Keys.

These would just be simple string values within the file, utilizing some placeholders available through Waystones depending on context, such placeholders could be
```
%waystones_outofrange% - How far out of range a player is from Waystone
%waystones_distance% - Player's total distance from Waystone
%waystones_name% - Name of Waystone in question
%waystones_range% - Range a Waystone is capable of being teleported to from
%waystones_status% - Active status of Waystone, seen in InfoEvent
%waystones_coords% - Coordinates of Waystone, as seen in current WarpKey lore
%waystones_countdown% - Countdown during warmup to Waystone warp
```
These wouldn't have to be global like CMI or PlaceholderAPI, but rather just available through this messages config, the messages would then be parsed to replace these instances when used within the actual events.

This could also allow for custom color codes to be used, though that may require some refactoring of the `Player.sendActionMessage()` function within PlayerUtils.kt

---

The message file could look something like
```yml
InfoMessage: "&bName: %waystones_name% | Status: %waystones_active% | Range: %waystones_range%"
InitWarpMessage: "&aWarping to %waystones_name% in %waystones_countdown% second(s)"
CancelWarpMessage: "&cWarp cancelled"
OutOfRangeMessage: "&c%waystones_name% is out of range (%waystones_outofrange% block(s))"
# etc. etc.
```

---

Slightly unrelated, but this could also open up to the idea of localization, with locale files in a directory holding the messages in different languages. Though I'm unsure as to how this is actually implemented.
